### ISSUE TITLE
Desktop client

### ISSUE THREAD

**Issue by trymeouteh** [judemont/CryptoTracker#4]
Please release this on Windows, MacOS and Linux!

**Comment by judemont** [comment]
Hi, in the last release I added installation files for linux.
Unfortunately I won't be able to add a release for windows and macos, because it requires a computer running the corresponding operating system, and I don't have one.

I'll try to create a virtual machine to achieve this, but I don't know if I'll be able to.
But if you really want to have a release for windows/macos you can always try to build it yourself.

**Comment by judemont** [comment]
Hi, I've created another application adapted specifically for desktop and web : [CryptoFlow](https://github.com/judemont/cryptoflow)
